---
- name: Stop service
  systemd:
    name: "{{ service_name }}"
    state: stopped
  become: yes

- name: Backup secrets
  copy:
    src: "{{ server_dir }}/.session-secret"
    dest: /tmp/.session-secret
    remote_src: yes
    force: yes
  become: yes
  become_user: "{{ remote_user }}"

- name: Make update
  include_role:
    name: common
    tasks_from: update

- name: Restore secrets
  copy:
    src: /tmp/.session-secret
    dest: "{{ server_dir }}/.session-secret"
    remote_src: yes
    force: yes
  become: yes
  become_user: "{{ remote_user }}"

- name: Start service
  systemd:
    name: "{{ service_name }}"
    state: started
    enabled: yes
  become: yes
