# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The '2' in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure('2') do |config|

  # Configure vm provider
  config.vm.provider 'virtualbox' do |v|
    # fix for bug https://github.com/hashicorp/vagrant/issues/9524
    v.customize ['modifyvm', :id, '--audio', 'none']
  end

  # Configure Ubuntu Machine
  config.vm.define 'omodlmy-net-test-server' do |machine|

    # Configure box
    machine.vm.box = 'ubuntu/bionic64'
    machine.vm.network 'private_network', ip: '172.22.22.22'

    # Provision: setup-virtual-env
    machine.vm.provision 'setup-virtual-env', type: 'ansible' do |ansible|
      ansible.playbook = 'setup-virtual-env.yml'
      ansible.groups = {
        'omodlmy-net-server' => ['omodlmy-net-test-server']
      }
    end

    # Provision: update-virtual-env
    machine.vm.provision 'update-virtual-env', type: 'ansible' do |ansible|
      ansible.playbook = 'update-virtual-env.yml'
      ansible.groups = {
        'omodlmy-net-server' => ['omodlmy-net-test-server']
      }
    end

    # Provision: update-production
    machine.vm.provision 'update-production', type: 'ansible' do |ansible|
      ansible.playbook = 'update-production.yml'
      ansible.groups = {
        'omodlmy-net-server' => ['omodlmy-net-test-server']
      }
    end

  end

end
